[package]
name = "rl_prototype"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.15.0"

[features]
default = ["vulkan", "tiles"]

empty = ["amethyst/empty"]
tiles = ["amethyst/tiles"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
